spring:
  main:
    banner-mode: off
  flyway:
    enabled: true
    baseline-on-migrate: true
    ignore-missing-migrations: true #After some time you'll want to archive migrations scripts
    locations: classpath:/db/migration/h2
    installed-by: mikas
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:payment-case-handling;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  jpa:
    database: h2
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none #Do not autogenerate SQL tables. Sometimes it might lead to suboptimal structures/types. Control you database!
    properties:
      hibernate:
        #Turn it on only when you need for analysing queries. Do not leave it on!
        generate_statistics: false
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false #Do not allow Spring to automagically fetch data from database
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: payment-case-handling

server:
  port: 8080
  servlet:
    context-path: /